"""Adding columns to grid

Revision ID: 060f9e50a447
Revises: 
Create Date: 2025-12-11 17:16:50.759859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '060f9e50a447'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('grid', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid', 'width')
    op.drop_column('grid', 'height')
    # ### end Alembic commands ###
